#!/bin/bash

set -o pipefail

SERVER_NAME="$1"
DEPLOY_DIR="/var/lib/minecraft/deploy"
SERVER_DIR="$DEPLOY_DIR/$SERVER_NAME"
SERVER_SERVICE_SCRIPT="$SERVER_DIR/service.sh"

if [[ ! -e "$SERVER_DIR" ]]; then
	echo "[1;31merror:[m Unknown server name '$SERVER_NAME'. Available servers:" >&2
	for i in "$DEPLOY_DIR/"*"/service.sh"; do
		echo " - $(basename "$(dirname "$i")")" >&2
	done
	exit 1
fi

run_server() {
	(
		cd "$SERVER_DIR"
		runuser -u minecraft -- \
			env \
				CALLED_FROM_SERVICE=true \
				SERVER_NAME="$SERVER_NAME" \
				"$SERVER_SERVICE_SCRIPT" \
				"$@"
	)
}

run_server attach
