#!/bin/bash

set -o pipefail
shopt -s nullglob

SERVER_NAME=$1
TMUX_SOCKET="/run/minecraft/tmux-$1"

if [[ ! -e "$TMUX_SOCKET" ]]; then
	echo "[1;31merror:[m Unknown server name '$SERVER_NAME'" >&2
	AVAILABLE=("/run/minecraft/tmux-"*)
	if [[ "${#AVAILABLE[@]}" == 0 ]]; then
		echo "There are currently no servers available." >&2
	else
		echo "Available servers: ${AVAILABLE[*]#"/run/minecraft/tmux-"}" >&2
	fi
	exit 1
fi

exec runuser -u minecraft -- tmux -S "$TMUX_SOCKET" attach-session
