#!/bin/bash

set -uo pipefail

umask 077
TTY="/dev/$(ps -p $$ -o tty=)"

################################################################
# Helper functions

function die() { echo "[1;31merror:[m $*" >&2; exit 1; }
function status() { echo "[1;33m$*[m"; }
function flush_stdin() { while read -r -t 0.01 empty_stdin; do true; done; }
function ask() {
	local response
	while true; do
		flush_stdin
		read -r -p "$* (Y/n) " response < "$TTY" || die "Error in read"
		case "${response,,}" in
			'') return 0 ;;
			y|yes) return 0 ;;
			n|no) return 1 ;;
			*) continue ;;
		esac
	done
}
# $1 = src, $2 = dest, $3 = owner, $4 = mode
function install_file() {
	cp    "$1" "$2" || die "Could not copy '$1' to '$2'"
	chown "$3" "$2" || die "Could not chown '$2'"
	chmod "$4" "$2" || die "Could not chmod '$2'"
}

################################################################
# Ensure that all required tools are installed

abort=0
for i in jq git tmux rdiff-backup java; do
	if ! type "$i" &>/dev/null; then
		echo "[1;31mmissing: [1;33m$i[m" >&2
		abort=1
	fi
done

[[ "$abort" == "0" ]] \
	|| die "Please install the missing tools first."


################################################################
# Ensure EULA is accepted

status "Agree to Mojang EULA"
echo "You have to agree to Mojang's EULA to use the server software."
echo "It is available here: https://account.mojang.com/documents/minecraft_eula"
ask "Do you agree to the EULA?" \
	|| die "Installation aborted. EULA must be accepted to continue." ;;


################################################################
# Ensure root access

[[ $EUID == 0 ]] || die "Must be root for system-wide installation."


################################################################
# Create minecraft user if necessary

if ! getent passwd minecraft &>/dev/null; then
	status "Creating minecraft user"
	useradd --system --home-dir /var/lib/minecraft --no-create-home minecraft \
		|| die "Could not create user 'minecraft'"
fi

mkdir -p /var/lib/minecraft
chmod 700 /var/lib/minecraft
chown minecraft: /var/lib/minecraft


################################################################
# Setup repository

cd ~minecraft \
	|| die "Could not change into ~minecraft"

if [[ -e deploy ]]; then
	status "Updating deploy repository"
	runuser -u minecraft -- git -C deploy pull \
		|| die "Could not pull repository"
else
	status "Cloning deploy repository"
	runuser -u minecraft -- git clone "https://github.com/oddlama/minecraft-server" deploy \
		|| die "Could not clone repository"
fi

cd deploy \
	|| die "Could not change into deploy directory"

status "Configuring server"
install_file <(echo "eula=true") server/eula.txt minecraft: 600

for d in $(find contrib/default_config -type d -printf '%P\n'); do
	mkdir -m700 "$d" || die "Could not create directory '$d'"
	chown minecraft: "$d" || die "Could not chown directory '$d'"
done

for f in $(find contrib/default_config -type f -printf '%P\n'); do
	install_file contrib/default_config/"$f" "$f" minecraft: 600
done

echo
echo "Depending on your player base, you might want to allow certain gamplay"
echo "exploits on your server. These are fixed by default in PaperMC, but would"
echo "allow your players to build certain vanilla machines (TNT blast chambers,"
echo "bedrock removal, ...)."
echo
echo "Our personal recommendation is to answer with yes to all of these questions."
echo

if ask "Allow headless pistons and bedrock breaking?"; then
	sed -i 's|allow-headless-pistons: false|allow-headless-pistons: true|' server/config/paper-global.yml \
		|| die "Could not replace allow-headless-pistons config"
	sed -i 's|allow-permanent-block-break-exploits: false|allow-permanent-block-break-exploits: true|' server/config/paper-global.yml \
		|| die "Could not replace allow-permanent-block-break-exploits config"
fi

if ask "Allow piston TNT duping?"; then
	sed -i 's|allow-piston-duplication: false|allow-piston-duplication: true|' server/config/paper-global.yml \
		|| die "Could not replace allow-piston-duplication config"
fi

if ask "Enable Anti-XRAY?"; then
	sed -i 's|false # ANTI_XRAY|true|' server/config/paper-world-defaults.yml \
		|| die "Could not replace ANTI_XRAY config"
else
	sed -i 's|false # ANTI_XRAY|false|' server/config/paper-world-defaults.yml \
		|| die "Could not replace ANTI_XRAY config"
fi

if ask "Replenish loot in loot chests after 1-2 realtime days?"; then
	sed -i 's|auto-replenish: false|auto-replenish: true|' server/config/paper-world-defaults.yml \
		|| die "Could not replace auto-replenish config"
fi

if ask "Disable hopper item move event to reduce lag?"; then
	sed -i 's|disable-move-event: false|disable-move-event: true|' server/config/paper-world-defaults.yml \
		|| die "Could not replace disable-move-event config"
fi

if ask "Increase view-distance to 15 chunks?"; then
	sed -i 's|view-distance=10|view-distance=15|' server/server.properties \
		|| die "Could not replace view-distance config"
fi


runuser -u minecraft -- ./update.sh < "$TTY" \
	|| die "Could not update server files"


################################################################
# Install systemd services

status "Installing service files"
./contrib/install.sh < "$TTY" \
	|| die "Error while installing service files"


################################################################
# Enable and start services

echo "[33mThe script would now enable and start the system services. If you want to"
echo "adjust any proxy related configuration, you may want to start them manually"
echo "at a later point in time.[m"
if ask "Enable and start system services?"; then
	status "Starting services ..."
	systemctl enable --now minecraft-server minecraft-proxy < "$TTY" \
		|| die "Error while enabling services"
else
	echo "[1m===============================================================================[m"
	echo "[1;33mMake sure to later execute the following command:"
	echo "[1;32m    systemctl enable --now minecraft-server minecraft-proxy[m"
	echo "[1m===============================================================================[m"
fi


################################################################
# Appendix

cat <<EOF
[1m===============================================================================[m
[1;32mInstallation successful![m
Both the proxy and main server have successfully been enabled! The actual
minecraft server will be started, when a player connects via the proxy.

Please make sure that TCP port 25565 (server), 25566 (multiplex 1) and 8100
(bluemap webserver) are exposed to the internet via a port-foward or similar
mechanism. If you want to change your server configuration, please do so now.

For more information, visit https://github.com/oddlama/minecraft-server
[1m===============================================================================[m
EOF
