#!/bin/bash

set -uo pipefail

umask 077
function die() { echo "[1;31merror:[m $*" >&2; exit 1; }
function status() { echo "[1m$*[m"; }
TTY="/dev/$(ps -p $$ -o tty=)"

################################################################
# Ensure that all required tools are installed

abort=0
for i in jq git tmux rdiff-backup java; do
	if ! type "$i" &>/dev/null; then
		echo "[1;31mmissing: [1;33m$i[m" >&2
		abort=1
	fi
done

[[ "$abort" == "0" ]] \
	|| die "Please install the missing tools first."


################################################################
# Ensure EULA is accepted

status "Agree to Mojang EULA"
echo "You have to agree to Mojang's EULA to use the server software."
echo "It is available here: https://account.mojang.com/documents/minecraft_eula"
read -r -p "Do you agree to the EULA? (Y/n) " response < "$TTY" || die "Error in read"
case "${response,,}" in
	''|y|yes) ;;
	*) die "Installation aborted. EULA must be accepted to continue." ;;
esac


################################################################
# Ensure root access

[[ $EUID == 0 ]] || die "Must be root for system-wide installation."


################################################################
# Create minecraft user if necessary

if ! getent passwd minecraft &>/dev/null; then
	status "Creating minecraft user"
	useradd --system --home-dir /var/lib/minecraft --no-create-home minecraft \
		|| die "Could not create user 'minecraft'"
fi

mkdir -p /var/lib/minecraft
chmod 700 /var/lib/minecraft
chown minecraft: /var/lib/minecraft


################################################################
# Setup repository

status "Cloning deploy repository"
cd ~minecraft \
	|| die "Could not change into ~minecraft"
runuser -u minecraft git clone "https://github.com/oddlama/minecraft-server" deploy \
	|| die "Could not clone repository"

status "Updating server and plugins"
runuser -u minecraft ./update.sh \
	|| die "Could not update mincraft"

echo "eula=true" > server/eula.txt
chown minecraft: server/eula.txt


################################################################
# Install systemd services

status "Installing service files"
cd deploy \
	|| die "Could not change into deploy directory"
./install.sh \
	|| die "Error while installing service files"


################################################################
# Enable and start services

systemctl enable --now minecraft-server minecraft-proxy \
	|| die "Error while enabling services"
