#!/bin/bash

set -uo pipefail

umask 077
function die() { echo "[1;31merror:[m $*" >&2; exit 1; }
function status() { echo "[1;33m$*[m"; }
TTY="/dev/$(ps -p $$ -o tty=)"

################################################################
# Ensure that all required tools are installed

abort=0
for i in jq git tmux rdiff-backup java; do
	if ! type "$i" &>/dev/null; then
		echo "[1;31mmissing: [1;33m$i[m" >&2
		abort=1
	fi
done

[[ "$abort" == "0" ]] \
	|| die "Please install the missing tools first."


################################################################
# Ensure EULA is accepted

status "Agree to Mojang EULA"
echo "You have to agree to Mojang's EULA to use the server software."
echo "It is available here: https://account.mojang.com/documents/minecraft_eula"
read -r -p "Do you agree to the EULA? (Y/n) " response < "$TTY" || die "Error in read"
case "${response,,}" in
	''|y|yes) ;;
	*) die "Installation aborted. EULA must be accepted to continue." ;;
esac


################################################################
# Ensure root access

[[ $EUID == 0 ]] || die "Must be root for system-wide installation."


################################################################
# Create minecraft user if necessary

if ! getent passwd minecraft &>/dev/null; then
	status "Creating minecraft user"
	useradd --system --home-dir /var/lib/minecraft --no-create-home minecraft \
		|| die "Could not create user 'minecraft'"
fi

mkdir -p /var/lib/minecraft
chmod 700 /var/lib/minecraft
chown minecraft: /var/lib/minecraft


################################################################
# Setup repository

cd ~minecraft \
	|| die "Could not change into ~minecraft"

if [[ -e deploy ]]; then
	status "Updating deploy repository"
	runuser -u minecraft -- git -C deploy pull \
		|| die "Could not pull repository"
else
	status "Cloning deploy repository"
	runuser -u minecraft -- git clone "https://github.com/oddlama/minecraft-server" deploy \
		|| die "Could not clone repository"
fi

cd deploy \
	|| die "Could not change into deploy directory"

echo "eula=true" > server/eula.txt
chown minecraft: server/eula.txt

runuser -u minecraft -- ./update.sh < "$TTY" \
	|| die "Could not update server files"


################################################################
# Install systemd services

status "Installing service files"
./contrib/install.sh < "$TTY" \
	|| die "Error while installing service files"


################################################################
# Enable and start services

status "Starting services ..."
systemctl enable --now minecraft-server minecraft-proxy < "$TTY" \
	|| die "Error while enabling services"


################################################################
# Appendix

echo "[1;32mInstallation successful![m"
echo "Both the proxy and main server have successfully been enabled!"
echo "The actual minecraft server will be started, when a player connects via the proxy."
echo
echo "Please make sure that port 25565 (and all multiplexer ports) are exposed"
echo "to the internet via a port-foward or similar mechanism."
echo "If you want to change your server configuration, please do so now."
echo
echo "To attach to the proxy or server console, use the following commands respectively:"
echo "  \$ minecraft-attach proxy"
echo "  \$ minecraft-attach server"
echo "[1;31mDo NOT quit this tmux terminal![m It has to stay open in the background"
echo "at all times. Instead, press 'C-b d' (Ctrl+b, then d) to detach again."
echo "If you closed it accidentally, restart the respective server with:"
echo "  systemctl restart minecraft-<whatever>"
echo
echo "To stop the server or proxy completely, you can use these commands respectively:"
echo "  \$ systemctl stop minecraft-server"
echo "  \$ systemctl stop minecraft-proxy"
echo "This is just temporary until either your physical server is restarted or you execute:"
echo "  \$ systemctl stop minecraft-server"
echo "  \$ systemctl stop minecraft-proxy"
echo
echo "For more information, visit https://github.com/oddlama/minecraft-server"
